### ISSUE TITLE
is docker-entrypoint.sh really needed?

### ISSUE THREAD

**Issue by jmcanterafonseca** [Bitergia/fiware-chanchan-docker#2]
https://github.com/Bitergia/fiware-chanchan-docker/blob/master/images/fiware-orion/master/docker-entrypoint.sh

seems not to be really needed, actually the orion image can run perfectly together with a mongo image using the following docker-compose.yml 

```
orion:
  image: fiware/orion
  links:
    - mongo
  ports:
    - "1026:1026"
  command: -dbhost mongo

mongo:
  image: mongo:2.6
```
