### ISSUE TITLE
[docker] idm firewall problem. connection refused from outside

### ISSUE THREAD

**Issue by ghost** [Bitergia/fiware-chanchan-docker#5]
Hi,

I cannot access idm from outside my network: Connection refused. I cannot access idm manager web horizon (:443) or API (:5000) from outside, says connection refused. So, in a place should be an idm firewall that is refusing all connections that are not in the same network. From my host computer with docker LAN, and from container localhost it works, but not with public IP from my computer or other computers. I intend to put this on a public server. How to disable this firewall?

I tried with /official docker file/ and no problem connecting outside: https://github.com/ging/fiware-idm/blob/master/extras/docker/Dockerfile

I also know how to put apache2 as web server for a django app with docker (in :80, didn't tried in :443), so I think there is not the problem.

The only changes on `local_settings.py` from official dockerfile seems to be:

`docker-entrypoint.sh:    sed -e "s@^ACCESS_CONTROL_URL = None@ACCESS_CONTROL_URL = 'http://${AUTHZFORCE_HOSTNAME}:${AUTHZFORCE_PORT}/authzforce/domains/${DOMAIN}/pap/policySet'@" -i /opt/fi-ware-idm/horizon/openstack_dashboard/local/local_settings.py`

`docker-entrypoint.sh:    sed -e "s@^ACCESS_CONTROL_MAGIC_KEY = None@ACCESS_CONTROL_MAGIC_KEY = '${MAGIC_KEY}'@" -i /opt/fi-ware-idm/horizon/openstack_dashboard/local/local_settings.py`

So I don't know how to find a solution

Thanks,
Pedro

**Comment by albertinisg** [comment]
Hi!

We actually don't have any firewall in this image at all. At first sight we've thought that the issue could be due to our [Apache redirect configuration](https://github.com/Bitergia/fiware-chanchan-docker/blob/master/images/idm-keyrock/4.3.0/idm.conf#L175), but I've tested it and it returns a `No route to host` instead of `Connection Refused`.

The difference between the Official one and ours is that, the official one doesn't use any Apache and it starts a python development environment.

Are you using the docker-compose provided in the repository? Have you tried to map the ports in the .yml file?

You can configure an environment variable in the .yml file to configure the Apache host like:

```
...
idm:
    image: bitergia/idm-keyrock:4.3.0
    links:
        - authzforce
    volumes:
        - /config
    expose:
        - "5000"
    environment:
        - IDM_KEYROCK_HOSTNAME="www.idmtest.com"
```

It would be great to have more details of the configuration you are using (docker-compose file, docker and docker-compose versions, etc), but mostly the .yml you are using to try to reproduce it :)

**Comment by ghost** [comment]
Let's simplify the problem so you can reproduce easily. Keystone part exposes port :5000, but this doesn't work with public ip, says "connection refused".

works:
`curl localhost:5000`
works (example of docker ip):
`curl 172.17.0.2:5000`
connection refused (example of LAN ip), from the same computer, and from another computer in same LAN:
`curl 192.168.1.32:5000`

But this problem is not present in official idm version, so it works with the other image.

Differences in how keystone is started:
- https://github.com/ging/fiware-idm/blob/master/extras/docker/docker-entrypoint.sh#L6
- https://github.com/Bitergia/fiware-chanchan-docker/blob/master/images/idm-keyrock/4.3.0/docker-entrypoint.sh#L115

My yaml file, I built myself all your images without important changes

```
pdp-service:
    #image: bitergia/authzforce:4.2.0
    build: bitergia-pdp
    container_name: pdp-container
    hostname: pdp-container
    expose:
        - "8080:8080"

idm-service:
    #image: bitergia/idm-keyrock:4.3.0
    build: bitergia-idm
    container_name: idm
    hostname: idm
    hostname: idm
    links:
        - pdp-service
    volumes:
        - /config
    expose:
        - "5000:5000"
        - "443:443"
    environment:
         - AUTHZFORCE_HOSTNAME=pdp-service
         - AUTHZFORCE_PORT=8080 
         - IDM_KEYROCK_HOSTNAME=idm
         - IDM_KEYROCK_PORT=443
         - MAGIC_KEY=daf26216c5434a0a80f392ed9165b3b4
         - WORKON_HOME=/opt/virtualenvs
         - APP_NAME="FIWAREdevGuide"
         - KEYSTONE_DB=/opt/fi-ware-idm/keystone/keystone.db
         - CONFIG_FILE=/config/idm2chanchan.json
         - PROVISION_FILE=/config/keystone_provision.py
         - KEYSTONE_VERBOSE=no

pep-service:
    #image: bitergia/pep-wilma:4.3.0
    build: bitergia-pep
    container_name: pep-container
    hostname: pep-container
    links:
#        - app
        - idm-service
        - pdp-service
    volumes_from:
        - idm-service:rw
    expose:
        - "1026:1026" #original is 8080
    environment:
        - AUTHZFORCE_HOSTNAME=pdp-service
        - AUTHZFORCE_PORT=8080 
        - IDM_KEYSTONE_HOSTNAME=idm-service
        - IDM_KEYSTONE_PORT=5000
#        - APP_HOSTNAME=app
        - APP_PORT=1026
        - PEP_USERNAME=pepproxy@test.com
        - PEP_PASSWORD=test
        - PEP_PORT=1026
        - IDM_USERNAME=user0@test.com
        - IDM_USERPASS=test
        - MAGIC_KEY=daf26216c5434a0a80f392ed9165b3b4
```

Can you reproduce that?

Other details:
- Docker version 1.9.0, build 76d6bc9
- docker-compose version: 1.5.0
